### ISSUE TITLE
why my code throws exception?

### ISSUE THREAD

**Issue by 2391003262** [netty/netty-incubator-codec-http3#197]
```
Http3HeadersFrame frame = new DefaultHttp3HeadersFrame();
            frame.headers().method("GET").path("/")
                    .authority(NetUtil.LOCALHOST4.getHostAddress() + ":" + 4431)
                    .scheme("https");
            ByteBuf byteBuf= Unpooled.copiedBuffer(new byte[0]);
            //Http3DataFrame dataFrame=new DefaultHttp3DataFrame(byteBuf);
            for (int i=1;i<=2;i++) {
                streamChannel.writeAndFlush(frame);
             //   streamChannel.writeAndFlush(dataFrame);
            }
```
I want to send more than one http request with single quic stream channel ,why it always throw exception blow?
```
io.netty.incubator.codec.http3.Http3Exception: Frame type unexpected
	at io.netty.incubator.codec.http3.Http3CodecUtils.connectionError(Http3CodecUtils.java:249)
	at io.netty.incubator.codec.http3.Http3FrameValidationUtils.frameTypeUnexpected(Http3FrameValidationUtils.java:92)
```
why a single stream channel can not send mutil request??
what's wrong with my code?

**Comment by 2391003262** [comment]
my code copyed from the example

**Comment by 2391003262** [comment]
```
package fjs.Example;

import fjs.clientpool.ClientPool;
import fjs.clientpool.NettyClientPool;
import fjs.future.Future;
import fjs.http.Request;
import fjs.http.Response;
import io.netty.bootstrap.Bootstrap;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;
import io.netty.channel.Channel;
import io.netty.channel.ChannelFutureListener;
import io.netty.channel.ChannelHandler;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.nio.NioDatagramChannel;
import io.netty.handler.ssl.util.InsecureTrustManagerFactory;
import io.netty.incubator.codec.http3.*;
import io.netty.incubator.codec.quic.QuicChannel;
import io.netty.incubator.codec.quic.QuicSslContext;
import io.netty.incubator.codec.quic.QuicSslContextBuilder;
import io.netty.incubator.codec.quic.QuicStreamChannel;
import io.netty.util.CharsetUtil;
import io.netty.util.NetUtil;
import io.netty.util.ReferenceCountUtil;
import kotlin.Pair;
import okhttp3.ConnectionPool;
import okhttp3.Headers;
import okhttp3.OkHttpClient;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.charset.Charset;
import java.util.Iterator;
import java.util.concurrent.*;
import java.util.logging.Logger;

public class Test2 {

    public static void main(String[] args) {
        NioEventLoopGroup group = new NioEventLoopGroup(1);

        try {
            QuicSslContext context = QuicSslContextBuilder.forClient()
                    .trustManager(InsecureTrustManagerFactory.INSTANCE)
                    .applicationProtocols(Http3.supportedApplicationProtocols()).build();
            ChannelHandler codec = Http3.newQuicClientCodecBuilder()
                    .sslContext(context)
                    .maxIdleTimeout(5000, TimeUnit.MILLISECONDS)
                    .initialMaxData(10000000)
                    .initialMaxStreamDataBidirectionalLocal(1000000)
                    .build();

            Bootstrap bs = new Bootstrap();
            Channel channel = bs.group(group)
                    .channel(NioDatagramChannel.class)
                    .handler(codec)
                    .bind(0).sync().channel();

            QuicChannel quicChannel = QuicChannel.newBootstrap(channel)
                    .handler(new Http3ClientConnectionHandler())
                    .remoteAddress(new InetSocketAddress(NetUtil.LOCALHOST4, 4431))
                    .connect()
                    .get();

            QuicStreamChannel streamChannel = Http3.newRequestStream(quicChannel,
                    new Http3RequestStreamInboundHandler() {
                        @Override
                        protected void channelRead(ChannelHandlerContext ctx,
                                                   Http3HeadersFrame frame, boolean isLast) {
                            releaseFrameAndCloseIfLast(ctx, frame, isLast);
                        }

                        @Override
                        protected void channelRead(ChannelHandlerContext ctx,
                                                   Http3DataFrame frame, boolean isLast) {
                            System.err.print(frame.content().toString(CharsetUtil.US_ASCII));
                            releaseFrameAndCloseIfLast(ctx, frame, isLast);
                        }

                        private void releaseFrameAndCloseIfLast(ChannelHandlerContext ctx,
                                                                Http3RequestStreamFrame frame, boolean isLast) {
                            ReferenceCountUtil.release(frame);
                            if (isLast) {
                                ctx.close();
                            }
                        }
                    }).sync().getNow();

            // Write the Header frame and send the FIN to mark the end of the request.
            // After this its not possible anymore to write any more data.
            Http3HeadersFrame frame = new DefaultHttp3HeadersFrame();
            frame.headers().method("GET").path("/")
                    .authority(NetUtil.LOCALHOST4.getHostAddress() + ":" + 4431)
                    .scheme("https");
            ByteBuf byteBuf= Unpooled.copiedBuffer(new byte[0]);
            //Http3DataFrame dataFrame=new DefaultHttp3DataFrame(byteBuf);
            for (int i=1;i<=2;i++) {
                streamChannel.writeAndFlush(frame);
             //   streamChannel.writeAndFlush(dataFrame);
            }
            streamChannel.writeAndFlush(frame);
            //streamChannel.writeAndFlush(dataFrame).addListener(QuicStreamChannel.SHUTDOWN_OUTPUT).sync();
            // Wait for the stream channel and quic channel to be closed (this will happen after we received the FIN).
            // After this is done we will close the underlying datagram channel.
            streamChannel.closeFuture().sync();

            // After we received the response lets also close the underlying QUIC channel and datagram channel.
            quicChannel.close().sync();
            channel.close().sync();
        }catch (Exception e){
            e.printStackTrace();
        }finally {
            group.shutdownGracefully();
        }

    }
}

```

**Comment by silence934** [comment]
你连续发送了两个header

**Comment by normanmaurer** [comment]
Closing...
